# Multi-cuisine dish database.
# Each entry: cuisine, cost (INR per plate-equivalent serving), waste_g (avg uneaten grams per adult serving),
# category (used for shopping-list aggregation), and spoilage_hours (how fast it turns risky at ~30-35C ambient).

DISH_DATABASE = {
    # ============================================================
    # SOUTH INDIAN
    # ============================================================
    "Idli": {"cuisine": "South Indian", "cost": 10, "waste_g": 18, "category": "Tiffin", "spoilage_hours": 6},
    "Idli Sambar": {"cuisine": "South Indian", "cost": 20, "waste_g": 22, "category": "Tiffin", "spoilage_hours": 5},
    "Mini Idli": {"cuisine": "South Indian", "cost": 12, "waste_g": 16, "category": "Tiffin", "spoilage_hours": 6},
    "Plain Dosa": {"cuisine": "South Indian", "cost": 18, "waste_g": 20, "category": "Tiffin", "spoilage_hours": 4},
    "Masala Dosa": {"cuisine": "South Indian", "cost": 28, "waste_g": 28, "category": "Tiffin", "spoilage_hours": 4},
    "Onion Dosa": {"cuisine": "South Indian", "cost": 26, "waste_g": 26, "category": "Tiffin", "spoilage_hours": 4},
    "Rava Dosa": {"cuisine": "South Indian", "cost": 24, "waste_g": 22, "category": "Tiffin", "spoilage_hours": 4},
    "Set Dosa": {"cuisine": "South Indian", "cost": 22, "waste_g": 20, "category": "Tiffin", "spoilage_hours": 4},
    "Uthappam": {"cuisine": "South Indian", "cost": 22, "waste_g": 24, "category": "Tiffin", "spoilage_hours": 4},
    "Pongal": {"cuisine": "South Indian", "cost": 18, "waste_g": 22, "category": "Tiffin", "spoilage_hours": 5},
    "Ven Pongal": {"cuisine": "South Indian", "cost": 18, "waste_g": 22, "category": "Tiffin", "spoilage_hours": 5},
    "Upma": {"cuisine": "South Indian", "cost": 14, "waste_g": 20, "category": "Tiffin", "spoilage_hours": 5},
    "Rava Upma": {"cuisine": "South Indian", "cost": 14, "waste_g": 20, "category": "Tiffin", "spoilage_hours": 5},
    "Vermicelli Upma": {"cuisine": "South Indian", "cost": 15, "waste_g": 18, "category": "Tiffin", "spoilage_hours": 5},
    "Appam": {"cuisine": "South Indian", "cost": 20, "waste_g": 22, "category": "Tiffin", "spoilage_hours": 4},
    "Idiyappam": {"cuisine": "South Indian", "cost": 18, "waste_g": 18, "category": "Tiffin", "spoilage_hours": 4},
    "Adai": {"cuisine": "South Indian", "cost": 20, "waste_g": 22, "category": "Tiffin", "spoilage_hours": 4},
    "Paniyaram": {"cuisine": "South Indian", "cost": 18, "waste_g": 18, "category": "Tiffin", "spoilage_hours": 4},
    "Ghee Roast Dosa": {"cuisine": "South Indian", "cost": 30, "waste_g": 26, "category": "Tiffin", "spoilage_hours": 4},
    "Pesarattu": {"cuisine": "South Indian", "cost": 22, "waste_g": 22, "category": "Tiffin", "spoilage_hours": 4},
    "Vegetable Biryani": {"cuisine": "South Indian", "cost": 35, "waste_g": 40, "category": "Rice", "spoilage_hours": 4},
    "Tomato Rice": {"cuisine": "South Indian", "cost": 20, "waste_g": 28, "category": "Rice", "spoilage_hours": 4},
    "Lemon Rice": {"cuisine": "South Indian", "cost": 16, "waste_g": 24, "category": "Rice", "spoilage_hours": 4},
    "Curd Rice": {"cuisine": "South Indian", "cost": 12, "waste_g": 25, "category": "Rice", "spoilage_hours": 3},
    "Tamarind Rice": {"cuisine": "South Indian", "cost": 16, "waste_g": 24, "category": "Rice", "spoilage_hours": 4},
    "Coconut Rice": {"cuisine": "South Indian", "cost": 18, "waste_g": 24, "category": "Rice", "spoilage_hours": 4},
    "Bisi Bele Bath": {"cuisine": "South Indian", "cost": 22, "waste_g": 30, "category": "Rice", "spoilage_hours": 4},
    "Vangi Bath": {"cuisine": "South Indian", "cost": 20, "waste_g": 28, "category": "Rice", "spoilage_hours": 4},
    "Sambar Rice": {"cuisine": "South Indian", "cost": 18, "waste_g": 28, "category": "Rice", "spoilage_hours": 4},
    "Rasam Rice": {"cuisine": "South Indian", "cost": 14, "waste_g": 26, "category": "Rice", "spoilage_hours": 4},
    "Plain Rice": {"cuisine": "South Indian", "cost": 10, "waste_g": 22, "category": "Rice", "spoilage_hours": 5},
    "Jeera Rice": {"cuisine": "South Indian", "cost": 14, "waste_g": 22, "category": "Rice", "spoilage_hours": 5},
    "Sambar": {"cuisine": "South Indian", "cost": 10, "waste_g": 14, "category": "Gravy", "spoilage_hours": 5},
    "Rasam": {"cuisine": "South Indian", "cost": 8, "waste_g": 10, "category": "Gravy", "spoilage_hours": 5},
    "Kara Kuzhambu": {"cuisine": "South Indian", "cost": 14, "waste_g": 16, "category": "Gravy", "spoilage_hours": 4},
    "Vatha Kuzhambu": {"cuisine": "South Indian", "cost": 14, "waste_g": 16, "category": "Gravy", "spoilage_hours": 4},
    "Mor Kuzhambu": {"cuisine": "South Indian", "cost": 12, "waste_g": 16, "category": "Gravy", "spoilage_hours": 3},
    "Kootu": {"cuisine": "South Indian", "cost": 12, "waste_g": 18, "category": "Gravy", "spoilage_hours": 4},
    "Avial": {"cuisine": "South Indian", "cost": 18, "waste_g": 20, "category": "Gravy", "spoilage_hours": 4},
    "Kalan": {"cuisine": "South Indian", "cost": 16, "waste_g": 18, "category": "Gravy", "spoilage_hours": 4},
    "Olan": {"cuisine": "South Indian", "cost": 16, "waste_g": 18, "category": "Gravy", "spoilage_hours": 4},
    "Poriyal": {"cuisine": "South Indian", "cost": 14, "waste_g": 16, "category": "Vegetable", "spoilage_hours": 5},
    "Cabbage Poriyal": {"cuisine": "South Indian", "cost": 14, "waste_g": 16, "category": "Vegetable", "spoilage_hours": 5},
    "Beans Poriyal": {"cuisine": "South Indian", "cost": 14, "waste_g": 16, "category": "Vegetable", "spoilage_hours": 5},
    "Carrot Poriyal": {"cuisine": "South Indian", "cost": 14, "waste_g": 16, "category": "Vegetable", "spoilage_hours": 5},
    "Beetroot Poriyal": {"cuisine": "South Indian", "cost": 14, "waste_g": 16, "category": "Vegetable", "spoilage_hours": 5},
    "Vazhakkai Poriyal": {"cuisine": "South Indian", "cost": 16, "waste_g": 16, "category": "Vegetable", "spoilage_hours": 5},
    "Pavakkai Fry": {"cuisine": "South Indian", "cost": 18, "waste_g": 14, "category": "Vegetable", "spoilage_hours": 5},
    "Potato Roast": {"cuisine": "South Indian", "cost": 16, "waste_g": 18, "category": "Vegetable", "spoilage_hours": 5},
    "Masala Vada": {"cuisine": "South Indian", "cost": 15, "waste_g": 15, "category": "Snack", "spoilage_hours": 8},
    "Medu Vada": {"cuisine": "South Indian", "cost": 16, "waste_g": 16, "category": "Snack", "spoilage_hours": 6},
    "Thattai": {"cuisine": "South Indian", "cost": 12, "waste_g": 10, "category": "Snack", "spoilage_hours": 12},
    "Murukku": {"cuisine": "South Indian", "cost": 12, "waste_g": 8, "category": "Snack", "spoilage_hours": 24},
    "Bonda": {"cuisine": "South Indian", "cost": 14, "waste_g": 14, "category": "Snack", "spoilage_hours": 6},
    "Banana Chips": {"cuisine": "South Indian", "cost": 10, "waste_g": 6, "category": "Snack", "spoilage_hours": 24},
    "Paal Payasam": {"cuisine": "South Indian", "cost": 25, "waste_g": 50, "category": "Dessert", "spoilage_hours": 3},
    "Semiya Payasam": {"cuisine": "South Indian", "cost": 22, "waste_g": 45, "category": "Dessert", "spoilage_hours": 3},
    "Pal Kozhukattai": {"cuisine": "South Indian", "cost": 20, "waste_g": 35, "category": "Dessert", "spoilage_hours": 4},
    "Kesari": {"cuisine": "South Indian", "cost": 18, "waste_g": 30, "category": "Dessert", "spoilage_hours": 6},
    "Mysore Pak": {"cuisine": "South Indian", "cost": 26, "waste_g": 15, "category": "Dessert", "spoilage_hours": 24},
    "Halwa": {"cuisine": "South Indian", "cost": 20, "waste_g": 25, "category": "Dessert", "spoilage_hours": 8},
    "Filter Coffee": {"cuisine": "South Indian", "cost": 10, "waste_g": 30, "category": "Beverage", "spoilage_hours": 2},
    "Buttermilk": {"cuisine": "South Indian", "cost": 8, "waste_g": 35, "category": "Beverage", "spoilage_hours": 3},
    "Tender Coconut": {"cuisine": "South Indian", "cost": 30, "waste_g": 10, "category": "Beverage", "spoilage_hours": 6},
    "Pickle": {"cuisine": "South Indian", "cost": 5, "waste_g": 4, "category": "Accompaniment", "spoilage_hours": 48},
    "Papad": {"cuisine": "South Indian", "cost": 6, "waste_g": 5, "category": "Accompaniment", "spoilage_hours": 24},
    "Appalam": {"cuisine": "South Indian", "cost": 6, "waste_g": 5, "category": "Accompaniment", "spoilage_hours": 24},
    "Coconut Chutney": {"cuisine": "South Indian", "cost": 8, "waste_g": 12, "category": "Accompaniment", "spoilage_hours": 4},
    "Tomato Chutney": {"cuisine": "South Indian", "cost": 8, "waste_g": 12, "category": "Accompaniment", "spoilage_hours": 4},
    "Mint Chutney": {"cuisine": "South Indian", "cost": 8, "waste_g": 10, "category": "Accompaniment", "spoilage_hours": 4},
    "Chettinad Chicken Curry": {"cuisine": "South Indian", "cost": 55, "waste_g": 35, "category": "Non-Veg Gravy", "spoilage_hours": 3},
    "Fish Curry": {"cuisine": "South Indian", "cost": 60, "waste_g": 35, "category": "Non-Veg Gravy", "spoilage_hours": 3},
    "Mutton Curry": {"cuisine": "South Indian", "cost": 70, "waste_g": 35, "category": "Non-Veg Gravy", "spoilage_hours": 3},
    "Prawn Roast": {"cuisine": "South Indian", "cost": 65, "waste_g": 30, "category": "Non-Veg Gravy", "spoilage_hours": 3},
    "Chicken 65": {"cuisine": "South Indian", "cost": 50, "waste_g": 25, "category": "Snack", "spoilage_hours": 4},
    "Egg Curry": {"cuisine": "South Indian", "cost": 28, "waste_g": 25, "category": "Non-Veg Gravy", "spoilage_hours": 4},

    # ============================================================
    # NORTH INDIAN
    # ============================================================
    "Paneer Butter Masala": {"cuisine": "North Indian", "cost": 45, "waste_g": 30, "category": "Gravy", "spoilage_hours": 3},
    "Paneer Tikka Masala": {"cuisine": "North Indian", "cost": 48, "waste_g": 30, "category": "Gravy", "spoilage_hours": 3},
    "Kadai Paneer": {"cuisine": "North Indian", "cost": 46, "waste_g": 28, "category": "Gravy", "spoilage_hours": 3},
    "Shahi Paneer": {"cuisine": "North Indian", "cost": 48, "waste_g": 32, "category": "Gravy", "spoilage_hours": 3},
    "Palak Paneer": {"cuisine": "North Indian", "cost": 42, "waste_g": 28, "category": "Gravy", "spoilage_hours": 3},
    "Matar Paneer": {"cuisine": "North Indian", "cost": 40, "waste_g": 28, "category": "Gravy", "spoilage_hours": 3},
    "Dal Makhani": {"cuisine": "North Indian", "cost": 30, "waste_g": 25, "category": "Gravy", "spoilage_hours": 4},
    "Dal Tadka": {"cuisine": "North Indian", "cost": 22, "waste_g": 20, "category": "Gravy", "spoilage_hours": 4},
    "Dal Fry": {"cuisine": "North Indian", "cost": 22, "waste_g": 20, "category": "Gravy", "spoilage_hours": 4},
    "Yellow Dal": {"cuisine": "North Indian", "cost": 18, "waste_g": 18, "category": "Gravy", "spoilage_hours": 4},
    "Chole": {"cuisine": "North Indian", "cost": 26, "waste_g": 24, "category": "Gravy", "spoilage_hours": 4},
    "Chole Bhature": {"cuisine": "North Indian", "cost": 40, "waste_g": 35, "category": "Combo", "spoilage_hours": 4},
    "Rajma": {"cuisine": "North Indian", "cost": 24, "waste_g": 22, "category": "Gravy", "spoilage_hours": 4},
    "Aloo Gobi": {"cuisine": "North Indian", "cost": 22, "waste_g": 20, "category": "Vegetable", "spoilage_hours": 5},
    "Aloo Matar": {"cuisine": "North Indian", "cost": 22, "waste_g": 20, "category": "Vegetable", "spoilage_hours": 5},
    "Mix Veg Curry": {"cuisine": "North Indian", "cost": 28, "waste_g": 24, "category": "Vegetable", "spoilage_hours": 4},
    "Bhindi Masala": {"cuisine": "North Indian", "cost": 24, "waste_g": 18, "category": "Vegetable", "spoilage_hours": 4},
    "Baingan Bharta": {"cuisine": "North Indian", "cost": 24, "waste_g": 20, "category": "Vegetable", "spoilage_hours": 4},
    "Kofta Curry": {"cuisine": "North Indian", "cost": 38, "waste_g": 28, "category": "Gravy", "spoilage_hours": 3},
    "Malai Kofta": {"cuisine": "North Indian", "cost": 42, "waste_g": 30, "category": "Gravy", "spoilage_hours": 3},
    "Butter Naan": {"cuisine": "North Indian", "cost": 18, "waste_g": 20, "category": "Bread", "spoilage_hours": 6},
    "Plain Naan": {"cuisine": "North Indian", "cost": 14, "waste_g": 18, "category": "Bread", "spoilage_hours": 6},
    "Garlic Naan": {"cuisine": "North Indian", "cost": 20, "waste_g": 20, "category": "Bread", "spoilage_hours": 6},
    "Tandoori Roti": {"cuisine": "North Indian", "cost": 12, "waste_g": 16, "category": "Bread", "spoilage_hours": 8},
    "Chapati": {"cuisine": "North Indian", "cost": 8, "waste_g": 14, "category": "Bread", "spoilage_hours": 8},
    "Paratha": {"cuisine": "North Indian", "cost": 16, "waste_g": 18, "category": "Bread", "spoilage_hours": 6},
    "Lachha Paratha": {"cuisine": "North Indian", "cost": 18, "waste_g": 18, "category": "Bread", "spoilage_hours": 6},
    "Kulcha": {"cuisine": "North Indian", "cost": 16, "waste_g": 16, "category": "Bread", "spoilage_hours": 6},
    "Veg Biryani (North)": {"cuisine": "North Indian", "cost": 38, "waste_g": 38, "category": "Rice", "spoilage_hours": 4},
    "Chicken Biryani": {"cuisine": "North Indian", "cost": 60, "waste_g": 45, "category": "Rice", "spoilage_hours": 3},
    "Mutton Biryani": {"cuisine": "North Indian", "cost": 75, "waste_g": 45, "category": "Rice", "spoilage_hours": 3},
    "Jeera Pulao": {"cuisine": "North Indian", "cost": 20, "waste_g": 22, "category": "Rice", "spoilage_hours": 5},
    "Veg Pulao": {"cuisine": "North Indian", "cost": 24, "waste_g": 24, "category": "Rice", "spoilage_hours": 5},
    "Kashmiri Pulao": {"cuisine": "North Indian", "cost": 32, "waste_g": 26, "category": "Rice", "spoilage_hours": 5},
    "Butter Chicken": {"cuisine": "North Indian", "cost": 65, "waste_g": 35, "category": "Non-Veg Gravy", "spoilage_hours": 3},
    "Chicken Tikka Masala": {"cuisine": "North Indian", "cost": 62, "waste_g": 32, "category": "Non-Veg Gravy", "spoilage_hours": 3},
    "Chicken Curry": {"cuisine": "North Indian", "cost": 55, "waste_g": 32, "category": "Non-Veg Gravy", "spoilage_hours": 3},
    "Mutton Rogan Josh": {"cuisine": "North Indian", "cost": 78, "waste_g": 32, "category": "Non-Veg Gravy", "spoilage_hours": 3},
    "Egg Bhurji": {"cuisine": "North Indian", "cost": 26, "waste_g": 20, "category": "Non-Veg Gravy", "spoilage_hours": 4},
    "Tandoori Chicken": {"cuisine": "North Indian", "cost": 60, "waste_g": 25, "category": "Tandoor", "spoilage_hours": 4},
    "Paneer Tikka": {"cuisine": "North Indian", "cost": 45, "waste_g": 18, "category": "Tandoor", "spoilage_hours": 5},
    "Hara Bhara Kebab": {"cuisine": "North Indian", "cost": 35, "waste_g": 16, "category": "Tandoor", "spoilage_hours": 5},
    "Seekh Kebab": {"cuisine": "North Indian", "cost": 50, "waste_g": 20, "category": "Tandoor", "spoilage_hours": 4},
    "Gulab Jamun": {"cuisine": "North Indian", "cost": 22, "waste_g": 15, "category": "Dessert", "spoilage_hours": 10},
    "Rasmalai": {"cuisine": "North Indian", "cost": 28, "waste_g": 35, "category": "Dessert", "spoilage_hours": 4},
    "Gajar Halwa": {"cuisine": "North Indian", "cost": 26, "waste_g": 28, "category": "Dessert", "spoilage_hours": 6},
    "Kheer": {"cuisine": "North Indian", "cost": 24, "waste_g": 45, "category": "Dessert", "spoilage_hours": 3},
    "Jalebi": {"cuisine": "North Indian", "cost": 20, "waste_g": 18, "category": "Dessert", "spoilage_hours": 8},
    "Rabri": {"cuisine": "North Indian", "cost": 30, "waste_g": 40, "category": "Dessert", "spoilage_hours": 3},
    "Kulfi": {"cuisine": "North Indian", "cost": 25, "waste_g": 20, "category": "Dessert", "spoilage_hours": 4},
    "Lassi": {"cuisine": "North Indian", "cost": 18, "waste_g": 40, "category": "Beverage", "spoilage_hours": 3},
    "Masala Chai": {"cuisine": "North Indian", "cost": 8, "waste_g": 30, "category": "Beverage", "spoilage_hours": 3},
    "Raita": {"cuisine": "North Indian", "cost": 12, "waste_g": 25, "category": "Accompaniment", "spoilage_hours": 3},
    "Salad": {"cuisine": "North Indian", "cost": 10, "waste_g": 20, "category": "Accompaniment", "spoilage_hours": 4},
    "Samosa": {"cuisine": "North Indian", "cost": 14, "waste_g": 18, "category": "Snack", "spoilage_hours": 6},
    "Pakora": {"cuisine": "North Indian", "cost": 14, "waste_g": 16, "category": "Snack", "spoilage_hours": 5},
    "Aloo Tikki": {"cuisine": "North Indian", "cost": 16, "waste_g": 16, "category": "Snack", "spoilage_hours": 5},
    "Pav Bhaji": {"cuisine": "North Indian", "cost": 30, "waste_g": 30, "category": "Combo", "spoilage_hours": 4},
    "Chaat": {"cuisine": "North Indian", "cost": 20, "waste_g": 22, "category": "Snack", "spoilage_hours": 3},

    # ============================================================
    # AMERICAN
    # ============================================================
    "Mac and Cheese": {"cuisine": "American", "cost": 32, "waste_g": 30, "category": "Pasta", "spoilage_hours": 4},
    "Veggie Burger Sliders": {"cuisine": "American", "cost": 45, "waste_g": 20, "category": "Sandwich", "spoilage_hours": 4},
    "Chicken Burger Sliders": {"cuisine": "American", "cost": 55, "waste_g": 22, "category": "Sandwich", "spoilage_hours": 3},
    "Beef Burger Sliders": {"cuisine": "American", "cost": 60, "waste_g": 22, "category": "Sandwich", "spoilage_hours": 3},
    "Classic Cheeseburger": {"cuisine": "American", "cost": 70, "waste_g": 25, "category": "Sandwich", "spoilage_hours": 3},
    "Grilled Chicken Sandwich": {"cuisine": "American", "cost": 60, "waste_g": 22, "category": "Sandwich", "spoilage_hours": 3},
    "Club Sandwich": {"cuisine": "American", "cost": 55, "waste_g": 20, "category": "Sandwich", "spoilage_hours": 4},
    "French Fries": {"cuisine": "American", "cost": 15, "waste_g": 35, "category": "Side", "spoilage_hours": 2},
    "Sweet Potato Fries": {"cuisine": "American", "cost": 20, "waste_g": 30, "category": "Side", "spoilage_hours": 2},
    "Onion Rings": {"cuisine": "American", "cost": 18, "waste_g": 28, "category": "Side", "spoilage_hours": 2},
    "Coleslaw": {"cuisine": "American", "cost": 14, "waste_g": 22, "category": "Side", "spoilage_hours": 4},
    "Mashed Potatoes": {"cuisine": "American", "cost": 16, "waste_g": 26, "category": "Side", "spoilage_hours": 4},
    "Mac Salad": {"cuisine": "American", "cost": 18, "waste_g": 24, "category": "Side", "spoilage_hours": 4},
    "Caesar Salad": {"cuisine": "American", "cost": 30, "waste_g": 26, "category": "Salad", "spoilage_hours": 3},
    "Garden Salad": {"cuisine": "American", "cost": 22, "waste_g": 24, "category": "Salad", "spoilage_hours": 4},
    "Cobb Salad": {"cuisine": "American", "cost": 35, "waste_g": 26, "category": "Salad", "spoilage_hours": 3},
    "BBQ Pulled Pork": {"cuisine": "American", "cost": 65, "waste_g": 30, "category": "BBQ", "spoilage_hours": 3},
    "BBQ Ribs": {"cuisine": "American", "cost": 85, "waste_g": 35, "category": "BBQ", "spoilage_hours": 3},
    "Grilled Chicken Wings": {"cuisine": "American", "cost": 55, "waste_g": 28, "category": "BBQ", "spoilage_hours": 3},
    "Buffalo Wings": {"cuisine": "American", "cost": 58, "waste_g": 28, "category": "BBQ", "spoilage_hours": 3},
    "Mozzarella Sticks": {"cuisine": "American", "cost": 35, "waste_g": 20, "category": "Appetizer", "spoilage_hours": 3},
    "Nachos": {"cuisine": "American", "cost": 40, "waste_g": 32, "category": "Appetizer", "spoilage_hours": 2},
    "Loaded Potato Skins": {"cuisine": "American", "cost": 38, "waste_g": 26, "category": "Appetizer", "spoilage_hours": 3},
    "Spinach Artichoke Dip": {"cuisine": "American", "cost": 32, "waste_g": 24, "category": "Appetizer", "spoilage_hours": 3},
    "Margherita Pizza": {"cuisine": "American", "cost": 50, "waste_g": 30, "category": "Pizza", "spoilage_hours": 4},
    "Pepperoni Pizza": {"cuisine": "American", "cost": 58, "waste_g": 30, "category": "Pizza", "spoilage_hours": 4},
    "Veggie Pizza": {"cuisine": "American", "cost": 52, "waste_g": 28, "category": "Pizza", "spoilage_hours": 4},
    "Pasta Alfredo": {"cuisine": "American", "cost": 42, "waste_g": 32, "category": "Pasta", "spoilage_hours": 3},
    "Pasta Marinara": {"cuisine": "American", "cost": 35, "waste_g": 28, "category": "Pasta", "spoilage_hours": 4},
    "Baked Ziti": {"cuisine": "American", "cost": 38, "waste_g": 30, "category": "Pasta", "spoilage_hours": 4},
    "Lasagna": {"cuisine": "American", "cost": 48, "waste_g": 32, "category": "Pasta", "spoilage_hours": 3},
    "Grilled Corn on the Cob": {"cuisine": "American", "cost": 18, "waste_g": 25, "category": "Side", "spoilage_hours": 4},
    "Baked Beans": {"cuisine": "American", "cost": 16, "waste_g": 22, "category": "Side", "spoilage_hours": 5},
    "Clam Chowder": {"cuisine": "American", "cost": 38, "waste_g": 35, "category": "Soup", "spoilage_hours": 2},
    "Tomato Soup": {"cuisine": "American", "cost": 20, "waste_g": 30, "category": "Soup", "spoilage_hours": 3},
    "Chicken Noodle Soup": {"cuisine": "American", "cost": 25, "waste_g": 30, "category": "Soup", "spoilage_hours": 3},
    "Hot Dogs": {"cuisine": "American", "cost": 30, "waste_g": 18, "category": "Sandwich", "spoilage_hours": 4},
    "Grilled Steak": {"cuisine": "American", "cost": 95, "waste_g": 28, "category": "BBQ", "spoilage_hours": 3},
    "Mashed Sweet Potato": {"cuisine": "American", "cost": 18, "waste_g": 26, "category": "Side", "spoilage_hours": 4},
    "Chocolate Brownies": {"cuisine": "American", "cost": 28, "waste_g": 12, "category": "Dessert", "spoilage_hours": 12},
    "Chocolate Chip Cookies": {"cuisine": "American", "cost": 18, "waste_g": 8, "category": "Dessert", "spoilage_hours": 24},
    "Apple Pie": {"cuisine": "American", "cost": 32, "waste_g": 22, "category": "Dessert", "spoilage_hours": 8},
    "Cheesecake": {"cuisine": "American", "cost": 40, "waste_g": 25, "category": "Dessert", "spoilage_hours": 4},
    "Vanilla Ice Cream": {"cuisine": "American", "cost": 25, "waste_g": 30, "category": "Dessert", "spoilage_hours": 2},
    "Donuts": {"cuisine": "American", "cost": 20, "waste_g": 14, "category": "Dessert", "spoilage_hours": 10},
    "Pancakes": {"cuisine": "American", "cost": 28, "waste_g": 24, "category": "Breakfast", "spoilage_hours": 4},
    "Waffles": {"cuisine": "American", "cost": 30, "waste_g": 22, "category": "Breakfast", "spoilage_hours": 4},
    "Scrambled Eggs": {"cuisine": "American", "cost": 20, "waste_g": 20, "category": "Breakfast", "spoilage_hours": 3},
    "Bacon": {"cuisine": "American", "cost": 35, "waste_g": 14, "category": "Breakfast", "spoilage_hours": 4},
    "Hash Browns": {"cuisine": "American", "cost": 18, "waste_g": 24, "category": "Breakfast", "spoilage_hours": 4},
    "French Toast": {"cuisine": "American", "cost": 26, "waste_g": 22, "category": "Breakfast", "spoilage_hours": 4},
    "Lemonade": {"cuisine": "American", "cost": 12, "waste_g": 35, "category": "Beverage", "spoilage_hours": 6},
    "Iced Tea": {"cuisine": "American", "cost": 10, "waste_g": 35, "category": "Beverage", "spoilage_hours": 6},
    "Milkshake": {"cuisine": "American", "cost": 30, "waste_g": 30, "category": "Beverage", "spoilage_hours": 3},
}

def get_dish_meta(item):
    if item in DISH_DATABASE:
        meta = dict(DISH_DATABASE[item])
        meta["known"] = True
        return meta
    return {
        "cuisine": "South Indian",
        "cost": 28,
        "waste_g": 22,
        "category": "Other",
        "spoilage_hours": 5,
        "known": False,
    }

def search_dishes(query, limit=8):
    if not query:
        return []
    q = query.lower()
    matches = [name for name in DISH_DATABASE if q in name.lower()]
    matches.sort(key=lambda n: (not n.lower().startswith(q), n))
    return matches[:limit]